---
title: BIDS for behavioral studies
aliases:
  - "/behavioral/2024-05-23/index.html"
description: "How to store your data in bids structure if you are using psychtoolbox"
image: ../../images/thumbnails/bids-for-behavioral-studies.svg
categories: [BIDS, Behavioral]
author: CY
date: 2024-05-23
code-links:
  - text: "Scripts on GitHub"
    icon: github
    href: https://github.com/visualneuroscience/visualneuroscience.github.io/tree/main/behavioral/bids-behavioral
---

## Resources

[Behavioral experiments (with no neural recordings) - Brain Imaging Data Structure v1.9.0](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/behavioral-experiments.html)

## Software

[bids-matlab](https://github.com/bids-standard/bids-matlab) \|

[bids-starter-kit on GitHub](https://github.com/bids-standard/bids-starter-kit) \|

[JSONio on GitHub](https://github.com/gllmflndn/JSONio)

## How to implement

You may use the template in the BIDS starter kit (bids-starter-kit/general). Simply copy the corresponding mat file and modify the variables for your project.

### After preprocessing

create_events_tsv_json_full.m

### Before finalizing everything

createBIDS_participants_tsv.m

createBIDS_dataset_description_json.m

### Pipeline for transriv project as an example

-   Add ‘transriv-bids’ to matlab path

-   Go to the root_dir or use the full path of root_dir as input to the functions

-   Preprocess data from a subject with [`createBIDS_beh_after_preprocessing.m`](createBIDS_beh_after_preprocessing.m){download="createBIDS_beh_after_preprocessing.m"} (it needs [`getBIDSdirectory.m`](getBIDSdirectory.m){download="getBIDSdirectory.m"} on the MATLAB path):

```matlab
createBIDS_beh_after_preprocessing(root_dir, 'transriv', 'S001', 'Rivalry', 'GG')
```

-   Create dataset files by running [`transriv_finalizeBIDS.m`](transriv_finalizeBIDS.m){download="transriv_finalizeBIDS.m"} (when data collection is finished)

The folder structure based on BIDS:

```text
root_dir
  └─ transriv
        ├─ participants.xlsx
        ├─ participants.tsv
        ├─ participants.json
        ├─ sourcedata
        │     └─ sub-S001
        │         └─ ses-Rivalry
        │               └─ beh
        │                   └─ sub-S001_ses-Rivalry_run-GG_beh.mat
        └─ rawdata
             └─ sub-S001
                 └─ ses-Rivalry
                     └─ beh
                         ├─ sub-S001_ses-Rivalry_run-GG_beh.json
                         └─ sub-S001_ses-Rivalry_run-GG_beh.tsv
```

[Link to our GitHub repo containing relevant scripts](https://github.com/visualneuroscience/visualneuroscience.github.io/tree/main/behavioral/bids-behavioral)
