project:
  type: website
  output-dir: docs

website:
  title: "Visual Neuroscience Lab"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: behavioral.qmd
        text: Behavioral
      - href: displays.qmd
        text: Displays
      - href: labmeeting.qmd
        text: Labmeeting
      - href: mri.qmd
        text: MRI
      - href: people.qmd
        text: People
      - href: stats.qmd
        text: Stats
      - href: contribute.qmd
        text: how to contribute to the lab website
      - href: members.qmd
        text: lab members only
      - href: other_topics.qmd
        text: Other Topics
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - mri/neurodesktop/neurodesktop.qmd
      - section: "MRI: from DICOM to GLM Analysis"
        href: mri/from_DICOMS_to_GLM/Overview_fromDICOMtoGLM.qmd
        contents:
          - mri/from_DICOMS_to_GLM/DICOMtoBIDS.qmd
          - mri/from_DICOMS_to_GLM/ProvidingParticipantsWithTheirT1wFile.qmd
          - mri/from_DICOMS_to_GLM/defacing.qmd
          - mri/from_DICOMS_to_GLM/RemoveDenoisingScan.qmd
          - mri/from_DICOMS_to_GLM/run_fmriprep.qmd
          - mri/from_DICOMS_to_GLM/troubleshooting.qmd
      - section: "MRI"
        href: mri.qmd
        contents:
          - mri/3D-prints/3d-prints.qmd
          - mri/analysis/7t_analysis_on_neurodesk.qmd
          - mri/analysis/bids.qmd
          - mri/analysis/dicom_to_bids.qmd
          - mri/analysis/fmriprep.qmd
          - mri/analysis/freesurfer FSFAST.qmd
          - mri/mri-lab-setup-2023/index.qmd
          - mri/mri-lab-setup-2024/index.qmd
          - mri/physiology/index.qmd
      - section: "Behavioral"
        href: behavioral.qmd
        contents:
          - behavioral/2024-05-22/index.qmd
          - behavioral/2024-05-23/index.qmd
          - behavioral/chinrests/chinrests.qmd
      - section: "Other Topics"
        href: other_topics.qmd
        contents:
          - OtherTopics/CalculatingAPrioriPower.qmd
          - OtherTopics/displays/displays.qmd
          - people/stipends/index.qmd
          - people/coffee/index.qmd
          - people/compensation/compensation.qmd
          - people/leaving/index.qmd
          - people/writing/writing.qmd
      - OtherTopics/Labmeeting.qmd
      - OtherTopics/LabMembersOnly/LabMembersOnly.qmd
      - OtherTopics/ContributeWithR.qmd
      - archive.qmd
  #DO NOT EDIT BELOW THIS LINE
  page-footer:
    background: light
    right:
      - icon: github
        href: https://github.com/visualneuroscience
format:
  html:
    page-layout: full
    theme:
      light: main_theme.scss
    toc: true

editor: visual
