project:
  type: website
  output-dir: docs

website:
  title: "Visual Neuroscience Lab"
  back-to-top-navigation: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: neurodesk/neurodesktop.qmd
        text: Neurodesktop
      - href: behavioral.qmd
        text: Behavioral
      - href: labmeeting.qmd
        text: Labmeeting
      - href: dicom_to_glm.qmd
        text: DICOM to GLM
      - href: mri.qmd
        text: MRI
      - href: people.qmd
        text: People
      - href: other_topics.qmd
        text: Other Topics
      - href: archive.qmd
        text: Archive
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Neurodesktop"
        href: neurodesk/neurodesktop.qmd
      - section: "MRI: from DICOM to GLM Analysis"
        href: dicom_to_glm.qmd
        contents:
          - dicom_to_glm/Overview_fromDICOMtoGLM.qmd
          - dicom_to_glm/DICOMtoBIDS.qmd
          - dicom_to_glm/ProvidingParticipantsWithTheirT1wFile.qmd
          - dicom_to_glm/defacing.qmd
          - dicom_to_glm/RemoveDenoisingScan.qmd
          - dicom_to_glm/ckeck_IntendedFor_field.qmd
          - dicom_to_glm/run_fmriprep.qmd
          - dicom_to_glm/retinotopic_mapping.qmd
          - dicom_to_glm/first_level_glm_nilearn.qmd
          - dicom_to_glm/troubleshooting.qmd
      - section: "MRI"
        href: mri.qmd
        contents:
          - mri/MRI-Studies_general/mri-studies_general-information.qmd
          - mri/3D-prints/3d-prints.qmd
          - mri/analysis/7t_analysis_on_neurodesk.qmd
          - mri/analysis/bids.qmd
          - mri/analysis/fmriprep.qmd
          - mri/mni-space/mni-space.qmd
          - mri/mri-lab-setup-2023/index.qmd
          - mri/mri-lab-setup-2024/index.qmd
          - mri/physiology/index.qmd
      - section: "Behavioral"
        href: behavioral.qmd
        contents:
          - behavioral/2024-05-22/index.qmd
          - behavioral/2024-05-23/index.qmd
          - behavioral/chinrests/chinrests.qmd
      - section: "People"
        href: people.qmd
        contents: 
          - people/stipends/index.qmd
          - people/coffee/index.qmd
          - people/compensation/compensation.qmd
          - people/leaving/index.qmd
          - people/writing/writing.qmd
          - people/interns/index.qmd
          - people/interns/pflichtpraktikum.qmd
      - section: "Other Topics"
        href: other_topics.qmd
        contents:
          - OtherTopics/CalculatingAPrioriPower.qmd
          - OtherTopics/displays/displays.qmd
          - OtherTopics/ContributeWithR.qmd
          - OtherTopics/LabMembersOnly/LabMembersOnly.qmd
      - text: "Labmeeting"
        href: labmeeting/index.qmd
      - text: "Archive"
        href: archive.qmd
  #DO NOT EDIT BELOW THIS LINE
  page-footer:
    background: light
    right:
      - icon: github
        href: https://github.com/visualneuroscience
format:
  html:
    page-layout: full
    theme:
      light: main_theme.scss
    toc: true

editor: visual
