---
fontsize: 12pt
geometry: margin=3cm
title: Interns
description: "Information for starting as an intern"
author: NZ
categories: [People, Lab]
date: 05/08/2025
---

Interns are an integral part of our team and are treated as equal colleagues. However, there are specific rules related to internships that all of us must abide by. Below you will find an internship checklist, which should help you navigate the process.

# Internship checklist

## Before starting

-   [ ] Discuss the content of your project with the PI

-   [ ] Do the necessary paperwork and make sure you got an o.k. from the secretary's office, the HR department of the university or the international office (for international students).

    -   If you are a bachelor student doing a "Pflichtpraktikum" at the University of Graz, you can find the relevant information in the [Pflichtpraktikum Section](pflichtpraktikum.qmd).

## On the first day

-   [ ] Get an office key from the secretary's office

-   [ ] Have someone show you your desk

-   [ ] Do the safety briefing with a PTA or PI (form can be found [here](https://sharepoint.uni-graz.at/sites/602/_layouts/15/WopiFrame.aspx?sourcedoc=%7BEC8D17C7-17DF-4538-A235-C15504B41B1B%7D&file=Unterweisungen_Untersuchungsraum.pdf&action=default))

-   [ ] Join our lab's slack (ask someone to add you if you did not receive an invitation yet)

    -   Do not feel obliged to keep slack on all the time and silence your notifications for times when you don't want to be disturbed. Everyone in the lab has the right to have their own working hours and nobody expects anyone else to have the same ones.

-   [ ] Make sure you know the date and time of the lab meetings if you would like to attend them

-   [ ] Create a spreadsheet in any format where you note the dates and times you worked on the project. This is not meant to control you, but rather to make sure we do not overload you with work.

-   [ ] If you would like to appear as intern on our lab's [official website](https://neurovision.uni-graz.at/en/contact-team/), please provide a square photograph of yourself (currently to MG)

## During the internship

-   [ ] Notify the PI when you reach your last 20 hours of your internship time, because we would love to hear about your project and its outcome in the lab meeting presentation.
-   [ ] If you prefer to use the office outside of the institute's typical opening hours (Sundays, holidays and late evenings), you can ask the secretary's office to activate your student card for entering the building.

## Before leaving

-   [ ] Make sure you check out the [leaving](../leaving/index.qmd) section. It is made primarily for doctoral students, but some things in there will apply to you as well.

-   [ ] Have the PI sign your documents.
