---
fontsize: 12pt
geometry: margin=3cm
title: "00 - Overview"
description: "Overview about how to get from DICOM files from the Scanner to your GLM Analysis"
number-sections: true
author: MG
date: 07/28/2025
---

# General

This page gives an overview and brief information about the necessary steps to get from your raw DICOM files to an Analysis. You can find more detailed information by navigating to the sub-pages by clicking on the caption of the respective point.

# Get your data

There are two ways how you get your data:

1)  Regular scanning time:

    -   you get the data as nifti files
    -   a few days later via `mri-dropoff` in the `J` drive ([Subpage for accessing other networks](../neurodesk/neurodesktop.qmd#sec-mountNetwork))
    -   [nifti conversion](#sec-convert) and [defacing](#sec-deface) generally are already done for you then (but check defacing anyway, sometimes this doesn´t work!)

2)  Scanning with Natalia

    -   we have the raw DICOM files
    -   conversion to niftis has to be done ([see here](#sec-convert))
    -   defacing has to be done ([see here](#sec-deface))

:::callout-warning
***IMPORTANT: Load the DICOM files to the server and delete them from any external/local device (USB-Stick, local storage of your computer, etc.) as soon as possible!!!***
:::

# DICOM-Files

-   the raw files from the scanner are DICOM-Files
-   in general, we primarily use `.nifti` files for the subsequent steps

$\to$ before we can continue, we need to convert `DICOM`- to `.nifti` files

::: callout-warning
## DELETE DICOMS FROM YOUR OWN DEVICES AS SOON AS POSSIBLE

***Load the DICOM files to the server and delete them from any external/local device (USB-Stick, local storage of your computer, etc.) as soon as possible!!!***
:::

# [DICOM to nifti](DICOMtoBIDS.qmd) {#sec-convert}

There are two options to convert DICOM to `.nifti` files:

1)   Older approach: using a script from Adam that can be [found here](https://github.com/adam-coates/dicom2bids) (or here: `/shared/website/dcm2bids_adam.sh`). All steps are also described in a [separate page](DICOMtoBIDS.qmd#sec-script)

2)  Newer approach: use the [BIDScoin workflow](https://bidscoin.readthedocs.io/en/latest/workflow.html) implemented in `/shared/website/dcm2bids_coiner.sh`. All steps are also described in a [separate page](DICOMtoBIDS.qmd#sec-bidscoiner)


both approaches should result in `.nifti` files in [BIDS](https://bids-specification.readthedocs.io/en/stable/introduction.html) format

# [Check the "IntendedFor" entry of the fmap's JSON file](check_IntendedFor_field.qmd)

-   "tells" [fmriPrep](run_fmriprep.qmd) where to apply distortion correction

-   ***depending on the fMRIprep version you plan to use, the field has to look slightly different!***

-   to avoid unnecessary problems and delays, it doesn´t harm to always check this field before running fMRIprep!

# [Distribute the T1w files to participants?](ProvidingParticipantsWithTheirT1wFile.qmd)

-   if you promised participants that they will get their T1w images, you should make sure that they really get them
-   this should be done before [defacing](defacing.qmd)
-   You should delete the "non-defaced" files either after you distributed them to the respective participants, or after your study ended

# [Defacing your data](defacing.qmd) {#sec-deface}

-   defaced data is necessary to savely run fMRIprep
-   Save faced T1w-files to give to your participants (if you got the data during regular scanning times, there should be a `faced` directory, but you should still make sure, that you have the faced T1w files if you need them for your participants!)
-   NEVER share data (e.g. on [open Neuro](https://openneuro.org/)) that was not defaced before!
-   Defacing is done with `pydeface` (Docker; Version 2.0.2)

# ([Remove denoising scan from your data](RemoveNoiseScan.qmd))

-   if a denoising sequence was used, but you don´t use denoising data, you might have to remove the last volume of each scan before continuing

# [fmriprep](run_fmriprep.qmd)

-   one of many [BIDS-Apps](https://bids.neuroimaging.io//tools/bids-apps.html) (that require [a BIDS-valid Dataset](https://bids-standard.github.io/bids-validator/))
-   combines various anatomical and functional preprocessing steps within one tool
-   necessary, time intense process

# [Probabilistic Retinotopic Mapping](retinotopic_mapping.qmd)

-   might be necessary to specifically test potential effects in specific visual areas (e.g. V1, V2, etc.)
-   provides retinotopy information (visual areas, eccentricity, etc.) even in the absence of dedicated retinotopy runs

# [first-level Analysis](first_level_glm_nilearn.qmd)

-   in the first level GLM you process the data of individual subjects
-   for each subject, you define/estimate a model that can explain your data
-   you define meaningful contrasts (e.g. your experimental conditions)
-   you account for potential confounds

# [Group-Level ROI Analysis](roi_analysis.qmd)

-   in the group-level ROI analysis, you extract relevevant (for your reasearch questions/hypothesis) information from your first level GLM
-   you should save this information in a format that allows you to later run your statistical analysis (e.g. as a `.csv` file)

# Statistical Analysis

-   with your extracted data (that are saved in a .csv file), you can now run your statistical analysis
