# Luminance measurement and gamma table

## General info

For luminance measurement on a certain screen (output screen), two monitors and a spectrophotometer are required. The Psychtoolbox script is run on the primary display monitor, while the luminance of the output screen is being measured. For the measurement, you need to stabilize the photometer on chinrest or anywhere in fromt of the output screen. In the worst case, a second person can hold the photometer at a constant distance. With the Script, 17 different levels of luminance for each of the three colors (R, G, B) and for all three colors together (grey), respectively, are displayed on the output screen. The luminance measures are typed into the command window. When the script is run without an error, it automatically saves the 17 values into a mat-file. Importantly, the room in which luminance is measured has to be as dark as possible. Thus, the primary display monitor ideally should be covered with dark tissue during the procedure if it is not isolated. ## Required softwares:

- Ideally Linux OS

- Matlab/Octave

- Psychtoolbox

## Operation 


- open `saveReadings.m` and edit the general info. If you want to customize the measurement, you may change the parameters as well.

- run `saveReadings.m` (alternatively, you may call directly the function `vals = saveMonitorPhotometerReadings(17, 'red')`)

- then, call the function to create gamma tables

    `[displayBaseline, displayRange, displayGamma, maxLevel] = createGammaFromSavedReadings(labName, screenName, 'plot', 0)`

Two gamma tables and two spline tables will be saved: one with RGB and one with gray. You need to decide which one is used (default for experiments: rgb_gamma). If you want to make further customization please dig into the scripts.


[Link to our GitHub repo containing relevant scripts](https://github.com/visualneuroscience/visualneuroscience.github.io/tree/main/luminancemeasurement/2024-05-22) 
