Journal club reading list (will be updated as I come across new papers that may be useful; suggestions are welcome!)

# fMRI methods

- Margulies et al., 2016: Hierarchy of areas based on the resting-state data: https://www.pnas.org/doi/10.1073/pnas.1608282113

- Glasser parcellation of the cortex, which everyone is using now: https://www.nature.com/articles/nature18933

- Multiple comparison correction methods for fMRI (no specific paper yet)

- [x] HCP processing pipeline and CIFTI format (alternative to fmriprep and state-of-the-art for 7 T preprocessing): https://www.sciencedirect.com/science/article/pii/S1053811913005053?via%3Dihub

- Resting-state connectivity of subcortical structures (including the claustrum) https://www.jneurosci.org/content/43/39/6609

- Neuroquery https://elifesciences.org/articles/53385

- Neurodesk https://www.nature.com/articles/s41592-023-02145-x

- White matter activations https://www.pnas.org/doi/10.1073/pnas.2219666120 

# Subjective experience

- [x] Self et al., 2019: ephys signatures of figure-ground segmentation in macaque V1: https://www.sciencedirect.com/science/article/pii/S0960982219301551

- Recent findings from Tsao lab: https://www.pnas.org/doi/10.1073/pnas.2221122120

- DMN and awareness: https://www.nature.com/articles/s41467-022-34410-6

- [x] Perceptography: https://www.biorxiv.org/content/10.1101/2022.10.24.513337v2

- [x] Perceptography in humans using visual illusions: https://www.science.org/doi/full/10.1126/sciadv.adj3906

# General methods

- [x] Statistical power (small sample sizes): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6267527/

- Statistical power: https://elifesciences.org/articles/62461

- Experimental methods: https://www.frontiersin.org/articles/10.3389/fnhum.2018.00421/full

- [x] Scientific writing: https://stevenpinker.com/files/pinker/files/descioli_pinker_2021_piled_modifiers.pdf

- Randomization techniques for statistical inference: permutation, bootstrapping, Monte Carlo simulations (no specific paper yet)

# AI

- [x] https://www.sciencedirect.com/science/article/pii/S2589004222011853?via%3Dihub
